# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-05 02:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccesssRecord',
            new_name='AccessRecord',
        ),
    ]
